version: "3.8"
services:
  db:
    image: postgres:16
    container_name: e-trader-backend-db-1
    environment:
      POSTGRES_DB: db01
      POSTGRES_USER: db01_user
      POSTGRES_PASSWORD: db01_password
    ports:
      - "5433:5432"
    networks:
      - ecommerce-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: e-trader-backend-backend-1
    ports:
      - "8082:8080" # Backend artık 8080'i tapulu malı yaptı
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db01
      SPRING_DATASOURCE_USERNAME: db01_user
      SPRING_DATASOURCE_PASSWORD: db01_password
    depends_on:
      - db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
