spring.application.name=backend

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db02
spring.datasource.username=db02_user
spring.datasource.password=db02_password
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration
spring.main.allow-bean-definition-overriding=true
server.address=0.0.0.0

# JWT Configuration
jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
jwt.expiration=3600000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=demirayhidrolik06@gmail.com
spring.mail.password=dtegmoogejuudjzn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Iyzico Configuration
iyzico.api-key=P9BSSZhMnF0Jlm9HtYkVHmX9piDf5Jud
iyzico.secret-key=F7uHXSmGFIn8fjoDNgvjmCW9XdPPaUPO
iyzico.base-url=https://api.iyzipay.com
iyzico.callback-url=https://api.demirayhidrolik.com/api/payments/callback
#https://api.demirayhidrolik.com/api/payments/callback
# Frontend URL (doÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂru link iÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ§in)
frontend.url=https://demirayhidrolik.com